chirpStack:
  sync:
    source:
      account:
      password:
      domain:
      organizationName:
    target:
      account:
      password:
      domain:
      organizationName:
      serviceProfileName:
      deviceProfileName:
    scheduled:
      application:
        enable: false
        duration: 0
        durationUnit:
      device:
        enable: false
        duration: 0
        durationUnit:
        applicationName:
        removeTargetRedundantDevice: false

